require 'pod/command/packagethk'
require 'cocoapods-packagerthk/user_interface/build_failed_report'
require 'cocoapods-packagerthk/builder'
require 'cocoapods-packagerthk/framework'
require 'cocoapods-packagerthk/mangle'
require 'cocoapods-packagerthk/pod_utils'
require 'cocoapods-packagerthk/spec_builder'
require 'cocoapods-packagerthk/symbols'
